export default [
	{ id: '1', imageName: '32.jpg', tag: 'Sun-Set' },
	{ id: '2', imageName: '33.jpg', tag: 'Sun-Set' },
	{ id: '3', imageName: '07.jpg', tag: 'Sun-Set' },
	{ id: '4', imageName: '34.jpg', tag: 'Sun-Set' },
	{ id: '5', imageName: '35.jpg', tag: 'Sun-Set' },
	{ id: '6', imageName: '36.jpg', tag: 'Sun-Set' },
	{ id: '7', imageName: '05.jpg', tag: 'Night-Photoshot'},
	{ id: '8', imageName: '06.jpg', tag: 'Night-Photoshot' },
	{ id: '9', imageName: '08.jpg', tag: 'Night-Photoshot' },
	{ id: '10', imageName: '44.jpg', tag: 'Night-Photoshot' },
	{ id: '11', imageName: '45.jpg', tag: 'Night-Photoshot' },
	{ id: '12', imageName: '46.jpg', tag: 'Night-Photoshot' },
	{ id: '13', imageName: '39.jpg', tag: 'Royal-Haweli' },
	{ id: '14', imageName: '40.jpg', tag: 'Royal-Haweli' },
	{ id: '15', imageName: '41.jpg', tag: 'Royal-Haweli' },
	{ id: '16', imageName: '42.jpg', tag: 'Royal-Haweli' },
	{ id: '17', imageName: '37.jpg', tag: 'Royal-Haweli' },
	{ id: '18', imageName: '38.jpg', tag: 'Royal-Haweli' },
];
