export default [
	{ id: '1', imageName: '71.jpg', tag: 'Wedding' },
	{ id: '2', imageName: '72.jpg', tag: 'Wedding' },
	{ id: '3', imageName: '73.jpg', tag: 'Wedding' },
	{ id: '4', imageName: '74.jpg', tag: 'Wedding' },
	{ id: '5', imageName: '75.jpg', tag: 'Wedding' },
	{ id: '6', imageName: '02.jpg', tag: 'Retro-View' },
	{ id: '7', imageName: '13.jpg', tag: 'Retro-View'},
	{ id: '8', imageName: '62.jpg', tag: 'Retro-View' },
	{ id: '9', imageName: '63.jpg', tag: 'Retro-View' },
	{ id: '10', imageName: '64.jpg', tag: 'Retro-View' },
	{ id: '11', imageName: '66.jpg', tag: 'Library' },
	{ id: '12', imageName: '67.jpg', tag: 'Library' },
	{ id: '13', imageName: '68.jpg', tag: 'Library' },
	{ id: '14', imageName: '69.jpg', tag: 'Library' },
	{ id: '15', imageName: '70.jpg', tag: 'Library' },
];
