export default [
	{ id: '1', imageName: '18.jpg', tag: 'Pre-Wedding' },
	{ id: '2', imageName: '19.jpg', tag: 'Post-Wedding' },
	{ id: '4', imageName: '21.jpg', tag: 'Post-Wedding' },
	{ id: '5', imageName: '22.jpg', tag: 'Post-Wedding' },
	{ id: '6', imageName: '23.jpg', tag: 'Pre-Wedding' },
	{ id: '7', imageName: '24.jpg', tag: 'Pre-Wedding' },
	{ id: '8', imageName: '25.jpg', tag: 'Pre-Wedding' },
	{ id: '9', imageName: '26.jpg', tag: 'Ring-Ceremony' },
	{ id: '10', imageName: '27.jpg', tag: 'Ring-Ceremony' },
	{ id: '11', imageName: '28.jpg', tag: 'Ring-Ceremony' },
	{ id: '12', imageName: '29.jpg', tag: 'Ring-Ceremony' },
	{ id: '13', imageName: '30.jpg', tag: 'Ring-Ceremony' },
	{ id: '14', imageName: '31.jpg', tag: 'Ring-Ceremony' },
];
